name: Netology AHJ Deployment

on:
  push:
    branches:
      - main # Здесь укажите вашу основную ветку
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Обновил до версии 2

      - name: Setup Node.js
        uses: actions/setup-node@v2 # Обновил до версии 2
        with:
          node-version: 14 # Версия Node.js, которая вам нужна

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run test
        run: npm run coverage

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Обновил до версии 3
        with:
          deploy_key: ${{ secrets.k2cwOAMKvceBO32HeBWBOSmOTn1O02bnnJn1+ZwSXZM }}
